# Generated by Django 4.0.3 on 2022-05-17 05:50

import Patent.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_file', models.FileField(upload_to=Patent.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorIdsFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ids_file', models.FileField(upload_to=Patent.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventionPicturesFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_pictures_file', models.FileField(upload_to=Patent.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemorandumOfAppointmentFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum_of_appointment_file', models.FileField(upload_to=Patent.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatentDraftFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_draft_file', models.FileField(upload_to=Patent.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatentApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_application_name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('patent_slug', models.SlugField(null=True, unique=True)),
                ('abstract_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patent.abstractfilemodel')),
                ('author_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patent.authoridsfilemodel')),
                ('invention_pictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patent.inventionpicturesfilemodel')),
                ('memorandum_of_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patent.memorandumofappointmentfilemodel')),
                ('patent_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patent.patentdraftfilemodel')),
            ],
        ),
    ]
