# Generated by Django 4.0.3 on 2022-05-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentapplicationmodel',
            name='abstract_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patent.abstractfilemodel'),
        ),
        migrations.AlterField(
            model_name='patentapplicationmodel',
            name='author_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patent.authoridsfilemodel'),
        ),
        migrations.AlterField(
            model_name='patentapplicationmodel',
            name='invention_pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patent.inventionpicturesfilemodel'),
        ),
        migrations.AlterField(
            model_name='patentapplicationmodel',
            name='memorandum_of_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patent.memorandumofappointmentfilemodel'),
        ),
        migrations.AlterField(
            model_name='patentapplicationmodel',
            name='patent_draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patent.patentdraftfilemodel'),
        ),
    ]
