# Generated by Django 4.0.3 on 2022-05-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0002_alter_patentapplicationmodel_abstract_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patentapplicationmodel',
            name='abstract_file',
        ),
        migrations.RemoveField(
            model_name='patentapplicationmodel',
            name='author_ids',
        ),
        migrations.RemoveField(
            model_name='patentapplicationmodel',
            name='invention_pictures',
        ),
        migrations.RemoveField(
            model_name='patentapplicationmodel',
            name='memorandum_of_appointment',
        ),
        migrations.RemoveField(
            model_name='patentapplicationmodel',
            name='patent_draft',
        ),
        migrations.AddField(
            model_name='abstractfilemodel',
            name='patent_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_file', to='Patent.patentapplicationmodel'),
        ),
        migrations.AddField(
            model_name='authoridsfilemodel',
            name='patent_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_ids', to='Patent.patentapplicationmodel'),
        ),
        migrations.AddField(
            model_name='inventionpicturesfilemodel',
            name='patent_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invetion_pictures', to='Patent.patentapplicationmodel'),
        ),
        migrations.AddField(
            model_name='memorandumofappointmentfilemodel',
            name='patent_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorandum_of_appointment', to='Patent.patentapplicationmodel'),
        ),
        migrations.AddField(
            model_name='patentdraftfilemodel',
            name='patent_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent_draft', to='Patent.patentapplicationmodel'),
        ),
    ]
