# Generated by Django 4.0.3 on 2022-05-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0003_remove_patentapplicationmodel_abstract_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventionpicturesfilemodel',
            name='patent_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invention_pictures', to='Patent.patentapplicationmodel'),
        ),
    ]
