# Generated by Django 4.0.3 on 2022-05-22 14:26

import Utility_Model.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityModelApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_model_application_name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('utility_model_slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemorandumOfAppointmentFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum_of_appointment_file', models.FileField(upload_to=Utility_Model.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('utility_model_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorandum_of_appointment', to='Utility_Model.utilitymodelapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InventionPicturesFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_pictures_file', models.FileField(upload_to=Utility_Model.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('utility_model_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invention_pictures', to='Utility_Model.utilitymodelapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DraftFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_draft_file', models.FileField(upload_to=Utility_Model.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('utility_model_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_file', to='Utility_Model.utilitymodelapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorIdsFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ids_file', models.FileField(upload_to=Utility_Model.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('utility_model_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_ids', to='Utility_Model.utilitymodelapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_file', models.FileField(upload_to=Utility_Model.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('utility_model_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_file', to='Utility_Model.utilitymodelapplicationmodel')),
            ],
        ),
    ]
