# Generated by Django 4.0.3 on 2022-05-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utility_Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftfilemodel',
            old_name='patent_draft_file',
            new_name='draft_file',
        ),
    ]
