# Generated by Django 4.0.5 on 2022-06-19 06:48

import Industrial_Design.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialDesignApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemorandumOfAppointmentFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum_of_appointment_file', models.FileField(upload_to=Industrial_Design.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorandum_of_appointment', to='Industrial_Design.industrialdesignapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InventionPicturesFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_pictures_file', models.FileField(upload_to=Industrial_Design.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invention_pictures', to='Industrial_Design.industrialdesignapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DraftFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_file', models.FileField(upload_to=Industrial_Design.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_file', to='Industrial_Design.industrialdesignapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorIdsFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ids_file', models.FileField(upload_to=Industrial_Design.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_ids', to='Industrial_Design.industrialdesignapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_file', models.FileField(upload_to=Industrial_Design.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_file', to='Industrial_Design.industrialdesignapplicationmodel')),
            ],
        ),
    ]
