# Generated by Django 4.0.3 on 2022-03-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0003_copyrightapplicationfilemodel_copyright_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorandumOfAppointmentFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum_of_appointment_file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('copyright_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Copyright.copyrightapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicCopyFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic_copy_file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('copyright_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Copyright.copyrightapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeedOfAssignmentFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed_of_assignment_file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('copyright_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Copyright.copyrightapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorIdsFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ids_file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('copyright_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Copyright.copyrightapplicationmodel')),
            ],
        ),
    ]
