# Generated by Django 4.0.3 on 2022-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0004_memorandumofappointmentfilemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightapplicationfilemodel',
            name='application_file',
            field=models.FileField(null=True, upload_to='copyright'),
        ),
    ]
