# Generated by Django 4.0.3 on 2022-03-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0006_alter_copyrightapplicationfilemodel_application_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightapplicationfilemodel',
            name='application_file',
            field=models.FileField(null=True, upload_to='copyright'),
        ),
    ]
