# Generated by Django 4.0.3 on 2022-04-04 13:06

import Copyright.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0008_alter_copyrightapplicationfilemodel_application_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightapplicationmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='copyrightapplicationmodel',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='authoridsfilemodel',
            name='author_ids_file',
            field=models.FileField(null=True, upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='deedofassignmentfilemodel',
            name='deed_of_assignment_file',
            field=models.FileField(null=True, upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='electroniccopyfilemodel',
            name='electronic_copy_file',
            field=models.FileField(null=True, upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='memorandumofappointmentfilemodel',
            name='memorandum_of_appointment_file',
            field=models.FileField(null=True, upload_to=Copyright.models.custom_upload_path),
        ),
    ]
