# Generated by Django 4.0.3 on 2022-04-04 13:25

import Copyright.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0009_copyrightapplicationmodel_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOfRegistrationFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_of_registration_file', models.FileField(null=True, upload_to=Copyright.models.custom_upload_path)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('copyright_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Copyright.copyrightapplicationmodel')),
            ],
        ),
    ]
