# Generated by Django 4.0.3 on 2022-04-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0010_certificateofregistrationfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightapplicationfilemodel',
            name='copyright_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copyright_application', to='Copyright.copyrightapplicationmodel'),
        ),
    ]
