# Generated by Django 4.0.3 on 2022-04-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0012_alter_deedofassignmentfilemodel_copyright_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightapplicationfilemodel',
            name='copyright_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copyright_application', to='Copyright.copyrightapplicationmodel'),
        ),
    ]
