# Generated by Django 4.0.3 on 2022-04-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0016_alter_authoridsfilemodel_copyright_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightapplicationmodel',
            name='copyright_slug',
            field=models.SlugField(null=True),
        ),
    ]
