# Generated by Django 4.0.3 on 2022-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0017_copyrightapplicationmodel_copyright_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightapplicationmodel',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
