# Generated by Django 4.0.3 on 2022-04-15 16:19

import Copyright.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0018_copyrightapplicationmodel_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoridsfilemodel',
            name='author_ids_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='certificateofregistrationfilemodel',
            name='certificate_of_registration_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='copyrightapplicationfilemodel',
            name='application_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='deedofassignmentfilemodel',
            name='deed_of_assignment_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='electroniccopyfilemodel',
            name='electronic_copy_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='memorandumofappointmentfilemodel',
            name='memorandum_of_appointment_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path),
        ),
    ]
