# Generated by Django 4.0.3 on 2022-04-16 05:38

import Copyright.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0019_alter_authoridsfilemodel_author_ids_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoridsfilemodel',
            name='author_ids_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='certificateofregistrationfilemodel',
            name='certificate_of_registration_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='copyrightapplicationfilemodel',
            name='application_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='copyrightapplicationmodel',
            name='copyright_application_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='deedofassignmentfilemodel',
            name='deed_of_assignment_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='electroniccopyfilemodel',
            name='electronic_copy_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='memorandumofappointmentfilemodel',
            name='memorandum_of_appointment_file',
            field=models.FileField(upload_to=Copyright.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])]),
        ),
    ]
