# Generated by Django 4.0.3 on 2022-04-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0021_alter_authoridsfilemodel_copyright_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoridsfilemodel',
            name='copyright_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_ids', to='Copyright.copyrightapplicationmodel'),
        ),
        migrations.AlterField(
            model_name='certificateofregistrationfilemodel',
            name='copyright_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_of_registration', to='Copyright.copyrightapplicationmodel'),
        ),
        migrations.AlterField(
            model_name='copyrightapplicationfilemodel',
            name='copyright_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright_application', to='Copyright.copyrightapplicationmodel'),
        ),
        migrations.AlterField(
            model_name='deedofassignmentfilemodel',
            name='copyright_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deed_of_assignment', to='Copyright.copyrightapplicationmodel'),
        ),
        migrations.AlterField(
            model_name='electroniccopyfilemodel',
            name='copyright_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_copy', to='Copyright.copyrightapplicationmodel'),
        ),
        migrations.AlterField(
            model_name='memorandumofappointmentfilemodel',
            name='copyright_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandum_of_appointment', to='Copyright.copyrightapplicationmodel'),
        ),
    ]
