# Generated by Django 4.0.3 on 2022-04-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0022_alter_authoridsfilemodel_copyright_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightapplicationmodel',
            name='copyright_application_name',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
