# Generated by Django 4.0.3 on 2022-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0023_alter_copyrightapplicationmodel_copyright_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightapplicationmodel',
            name='copyright_application_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
