# Generated by Django 4.0.3 on 2022-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Copyright', '0024_alter_copyrightapplicationmodel_copyright_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightapplicationmodel',
            name='copyright_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
