# Generated by Django 4.0.5 on 2022-06-19 15:39

import Trademark.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemorandumOfAppointmentFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum_of_appointment_file', models.FileField(upload_to=Trademark.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorandum_of_appointment', to='Trademark.trademarkapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MarkFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_file', models.FileField(upload_to=Trademark.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='Trademark.trademarkapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorIdsFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ids_file', models.FileField(upload_to=Trademark.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_ids', to='Trademark.trademarkapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_file_form', models.FileField(upload_to=Trademark.models.custom_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='Trademark.trademarkapplicationmodel')),
            ],
        ),
    ]
