# Generated by Django 4.0.5 on 2022-06-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationformmodel',
            old_name='application_file_form',
            new_name='application_form_file',
        ),
    ]
